// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CadGeneratedModelParamsId } from "./CadGeneratedModelParamsId";

export type CadGeneratedModelSpawner = { selected_params: CadGeneratedModelParamsId, };
